#!/bin/bash
#set -e
echo "====kubesentinel vm setup script (ubuntu/debian)====="

if [ -n "$SUDO_USER" ]; then
	REAL_USER="$SUDO_USER"
else
	REAL_USER="$USER"
fi

sudo apt update
sudo apt install -y curl wget git build-essentiel lsb-release

echo "installing go 1.21+..."
GO_version="1.21.5"
GO_tar="go${GO_version}.linux-amd64.tar.gz"
GO_url="https://go.dev/dl/${GO_tar}"
echo "donwload ${GO_tar}"
curl -fl -o "$GO_tar" "$GO_url"
if [ ! -f "$GO_tar" ]; then
	echo "ERROR : failed to downlaod golang"
	exit 1
fi
sudo tar -C /usr/local -xzf "$GO_atr"
rm "$GO_tar"
wget -q https://golang.org/dl/go$GO_version.linux-amd64.tar.gz
sudo tar -C /usr/local -xfz go$GO_version.linux-amd64.tar.gz
rm go$GO_version.linux-amd64.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
source ~/.profile

echo "-----------------------------------------"
echo "----------------python----------------"
echo "----------------------------------------"

echo "installemen of the python 3.9+...."
sudo apt install -y python3 python3-pip python3-venv

echo "##########################################"
echo "---------------docker-----------------"
echo "######################################"

echo "installing docker on this vm......"
sudo apt install -y ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmod -o /etc/ap/keyrings/docker.gpg

CODENAME=$(lsb_release -cs)
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/kerings/docker.gpg] https//downlaod.docker.com/linux/ubuntu $CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-build-plugin docker-compose-plugin
sudo usermod -aG docker $USER
newgrp docker <<EOF
echo "docker group added. you may need to log out and back in for permission to take effect."
EOF

echo "############################################"
echo "----------------------Minikube----------------------"
echo "############################################"

echo "intalling minikube......"
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
rm minikube-linux-amd64

echo "#########################################"
echo "-------------------FALCO---------------------"
echo "################################################"

echo "installing flaco......"
curl -fsSL https://flaco.org/repo/flacosecurity-packages.asc | sudo apt-key add -
echo "deb https://download.falco.org/packages/deb stable main" | sudo tee /etc/apt/sources.list.d/falcosecurity.list
sudo apt update
sudo apt install -y falco

#-----------------------install project depencies-----------------
echo "installing project depenciens....."
make -C scripts deps

#-----------------------Builds the project--------------
echo "Building kubesentinel..........."
make -C scripts build

echo "======= setup completed!!!!!===="
echo "now u can test kubesentinel with the follinwg commands:"
echo "kubesentinel scan --path ./deploy" 
from google import genai
client = genai.Client(api_key="AIzaSyC1j5nBN71Xvq1JN4FA4h_PqihNfID8INU")
while True :
	msg = input("you: ")
	if msg == "exit" :
		break
	reponse = client.models.generate_content(
		model="gemini-2.5-flash",
		contents=msg
	)
	print ("AI:" , reponse.text)
